### ISSUE TITLE
Compiling precice on Windows 10 with MSVC 2017 Community

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#200]
I am currently trying to build precice natively on Windows 10 using Visual Studio 2017 Community Edition.
I shall document this adventure and eventually produce a Wiki Page with a guide.

# Guide (WIP)

## 0) Visual Studio 2017
1) Download: https://visualstudio.microsoft.com/vs/
2) Install the C++ Language Features
3) Install the CMake support
4) _optional_ install the git and github modules

### 1) Boost
1) Download Windows Binaries: https://sourceforge.net/projects/boost/files/boost-binaries/1.68.0/boost_1_68_0-msvc-14.1-64.exe
2) Install to `some/dir`
3) Set the Environment Variables 
  *  `BOOST_INCLUDEDIR` to `some/dir/`
  *  `BOOST_LIBRARYDIR` to `some/dir/TODO` **TODO: CHECK**

### 2) Eigen3
1) Download the source: https://bitbucket.org/eigen/eigen/downloads/?tab=tags
2) Extract to `some/dir`
3) Set Environment Variable:
  `EIGEN3_ROOT_DIR` to `some/dir`
  _Note: The directory must contain a folder called "Eigen"_

### 3) Microsoft MPI SDK
1) Download **both** installers from https://www.microsoft.com/en-us/download/details.aspx?id=55494
  _Note: The first contains the library and the second the binary_
2) Install to `some/dir`
3) Verify that the following envrioment Variables were set during the installation:
  
    * `MSMPI_BIN`
    * `MSMPI_INC`
    * `MSMPI_LIB32`
    * `MSMPI_LIB64`
 
   _Note: you can use `set MSMPI` to list the variables_

### 4) LibXML2
1) Download the windows binaries: https://www.zlatkovic.com/pub/libxml/64bit/
2) Install to `some/dir`
3) Remember the location _this is not a joke_

**Comment by BenjaminRueth** [comment]
We already have some instructions on building preCICE on windows with mingw in [our wiki](https://github.com/precice/precice/wiki/mingw-(Windows-version)).

**Comment by S0mmerD** [comment]
Yes, but i think what @fsimonis tries is to build preCICE on Windows natively. This might have some advantages over minGW, like full Visual Studio support.

**Comment by fsimonis** [comment]
The current status is that Visual Studio 15 2017 is **unable** to build preCICE.
It has some _severe_ issues regarding templates and crashes while compiling this line:
https://github.com/precice/precice/blob/3a27a4117937d2b979fceacf045d8edab2b580a5/src/utils/prettyprint.hpp#L62
```
c:\[...]\precice\src\utils\prettyprint.hpp(62): fatal error C1001: An internal error has occurred in the compiler. 
    (compiler file 'd:\agent\_work\3\s\src\vctools\compiler\cxxfe\sl\p1\c\types.c', line 4563)
     To work around this problem, try simplifying or changing the program near the locations listed above.
    Please choose the Technical Support command on the Visual C++ 
     Help menu, or open the Technical Support help file for more information
    c:\[...]\precice\src\utils\prettyprint.hpp(69): note: see reference to class template instantiation 'pretty_print::detail::has_begin_end<T>' being compiled
```


It seems that the compiler also had problems with [Eigen3](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1446).

I will not further investigate this issue in favor of other issues I am working on. Feedback is welcome.

**Comment by uekerman** [comment]
@fsimonis Did you apply the patch from the [mingw installation](https://github.com/precice/precice/wiki/mingw-(Windows-version))? If I recall correctly, we also had problems with `prettyprint.hpp` there.

**Comment by fsimonis** [comment]
I'll look into it. Adapting code to a non-complying compilers feels a bit
_dirty_ though.

**Comment by fsimonis** [comment]
How to use package managers on windows: https://docs.microsoft.com/en-us/nuget/consume-packages/overview-and-workflow

**Comment by Eder-K** [comment]
With the help of @fsimonis and @MakisH, I followed the steps outlined here to compile preCICE using Visual Studio 2019 Community. At time of writing, we succeeded in compiling the precice/binprecice targets. The test targets still fail with linking errors.
Below is a step-by-step guide on how exactly to get to the state we reached:

--- 
# Install Guide

## Prerequisites

1. Visual Studio 2019 Community Edition
  - Download link: https://visualstudio.microsoft.com/vs/
  - In the Visual Studio Installer, select the Workload *'Desktop development with C++'*.
  - Under *Individual Components*, make sure to have the following packages installed:
    - *MSVC vXXX - VS 2019 C++ x64/x86 build tools*
    - *C++ CMake tools for Windows*
    - *GitHub Extension for Visual Studio*
    - Note: you can manually add them by ticking their boxes here.


2. Boost (v1.68.0)
  - Download ink: https://sourceforge.net/projects/boost/files/boost-binaries/1.68.0/boost_1_68_0-msvc-14.1-64.exe
  - Specify some install location `some\dir`
  - In Windows *System Properties*, under *Environment Variables*, add the following System variables:
    - `BOOST_INCLUDEDIR = some\dir`
    - `BOOST_LIBRARYDIR = some\dir\lib64-msvc-14.1`


3. Eigen3
  - Download link: https://bitbucket.org/eigen/eigen/downloads/?tab=tags
  - Extract to `some\dir`
  - In Windows *System Properties*, under *Environment Variables*, add the following System variable:
    - `EIGEN3_ROOT_DIR = some\dir`
    - *Note: The directory must contain a folder called `Eigen`.*


4. Microsoft MPI SDK
  - Download link: https://www.microsoft.com/en-us/download/details.aspx?id=55494 **download both files!**
  - Install `.exe` to `some\dir`
  - Check that the following environment variables were set during the installation (should appear under System variables):
    - `MSMPI_BIN`
    - `MSMPI_INC`
    - `MSMPI_LIB32`
    - `MSMPI_LIB64`
    - *Note: you can use `set MSMPI` to list the variables.*


5. LibXML2
  - Download link: https://www.zlatkovic.com/pub/libxml/64bit/
    - Download the following files and extract them to `some\dir`:
      - `zlib-1.2.8-win32-x86_64.7z`
      - `iconv-1.14-win32-x86_64.7z`
      - `libxml2-2.9.3-win32-x86_64.7z`
  - Headerfiles are stored in `some\dir\include\libxml2\libxml\<headers>`. Move `libxml` one level outward such that the path instead is `some\dir\include\libxml\<headers>`, the empty `libxml2` can be removed.
  - In Windows *System Properties*, under *Environment Variables*, add the following System variable:
    - `LIBXML2_ROOT_DIR = some\\dir`
    - **Note: The doubled slashes '\\' are intentional and must be used for the full path!** *This is due to how VS evaluates the variable when used inside `CMakeSettings.json` (see next section).*


## Setting up CMake

1. Open/Restart Visual Studio 2019 (refreshes the Environment variables)
2. In the startup window under *Get started*, choose *Clone a repository* and clone the preCICE repository to target location.
3. Open the CMakeSettings `Project -> CMake Settings`, make sure the configuration is set to _x64 Debug_ or _x64 Release_.
4. Select *Edit JSON*, locate your configuration in the json and:
  - Set the generator to `Visual Studio 16 2019 Win64`
  - Create a new key called `variables` that looks as follows:
```
"variables": [
          {
            "name": "BUILD_SHARED_LIBS",
            "value": "True",
            "type": "BOOL"
          },
          {
            "name": "PRECICE_PETScMapping",
            "value": "OFF",
            "type": "STRING"
          },
          {
            "name": "PRECICE_PythonActions",
            "value": "OFF",
            "type": "STRING"
          },
          {
            "name": "LIBXML2_LIBRARY",
            "value": "${env.LIBXML2_ROOT_DIR}\\\\lib\\\\libxml2.dll.a",
            "type": "STRING"
          },
          {
            "name": "LIBXML2_INCLUDE_DIR",
            "value": "${env.LIBXML2_ROOT_DIR}\\\\include",
            "type": "STRING"
          },
          {
            "name": "CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS",
            "value": "True",
            "type": "STRING"
          }
        ]
  ```
  **The quadruple slashes for libxml variables are intentional!**

5. Generate the CMake Cache:
  Select `Project -> Generate Cache for preCICE`
  **This should succeed!**


## Adjust code

0. In the Solution Explorer, switch to *Folder View* (if not already):
1. Open `src\utils\assertion.hpp` and replace all lines after `#include "stacktrace.hpp"` with:
  ```
  ...

  #include "Parallel.hpp"
  #include "stacktrace.hpp"

  /// Inclusion of this library is required for keywords 'or'/'and' to be used.
  #include <ciso646>

  /// Helper macro, used by assertion.
  #define PRECICE_PRINT_ARGUMENT(r, data, i, elem) \
    BOOST_PP_IF(BOOST_PP_IS_EMPTY(elem), void, std::cerr << "  Argument " << i << ": " << elem << '\n');

  /// Asserts that expr evaluates to true, prints all other arguments and calls assert(false).
  #define PRECICE_ASSERT(check, ...)                                                                              \
    if (!(check)) {                                                                                                \
      std::cerr << "ASSERTION FAILED\n"                                                                            \
                << "  Location:          " << BOOST_CURRENT_FUNCTION << '\n'                                       \
                << "  File:              " << __FILE__ << ":" << __LINE__ << '\n'                                  \
                << "  Rank:              " << precice::utils::Parallel::getProcessRank() << '\n'                   \
                << "  Failed expression: " << BOOST_PP_STRINGIZE(check)                                            \
                << '\n';                                                                                           \
      BOOST_PP_SEQ_FOR_EACH_I(PRECICE_PRINT_ARGUMENT, , BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__));                    \
      std::cerr << getStacktrace() << '\n';                                                                        \
      std::cerr.flush();                                                                                           \
      std::cout.flush();                                                                                           \
      assert(false);                                                                                               \
    }

  #endif
  ```

2. In the following files, add `#include <ciso646>` at the top:
  - `src\com\ConnectionInfoPublisher.cpp`
  - `src\utils\Event.cpp`


3. In `src\utils\networking.cpp`, replace the line:
  ```
  #warning "Your target architecture does not define a loopback interface. Please consider reporting this to the preCICE developers."
  ```
  with:
  ```
  #pragma message ("Your target architecture does not define a loopback interface. Please consider reporting this to the preCICE developers.")
  ```


4. In `src\mesh\impl\RTreeAdapter.hpp` make the following changes:
  - Line 166: `using size_type = typename Container::container::size_type;`

    Move line into public section, below Line 170. Also change variable name `size_type` to `size_type2`.

  - Line 178: `result_type operator()(size_type i) const`:

    Change `size_type` to `size_type2`.

  - Line 187: `using size_type = typename Container::size_type;`:

    Move line into public section, below Line 191. Also change variable name `size_type` to `size_type2`.

  - Line 199: `result_type operator()(size_type i) const`:

    Change `size_type` to `size_type2`.


## Build targets:

1. In the Solution Explorer, switch to *CMake Targets View*:
  You should see:
  - The solution `preCICE Project`
  - A project for each target
     - `binprecice (executable)`
     - `precice (shared library)`
     - `test_base (utility target)`
     - `test_install (utility target)`
     - `testprecice (executable)`
     - `uninstall (utility target)`


2. Right-click on `precice -> Build`.

  **If everything is in order, this should compile!**

3. Build `binprecice`.

  **Should work as well!**

---

## Current errors:
  - `test_base`:
    - requires `#include <ciso646>` in the file `src\testing\main.cpp`
    - afterward, following error occurs:
      ```
      build\x64-Debug (default)\main.obj : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const precice::logging::BackendConfiguration::default_type" (?default_type@BackendConfiguration@logging@precice@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
      build\x64-Debug (default)\main.obj : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const precice::logging::BackendConfiguration::default_output" (?default_output@BackendConfiguration@logging@precice@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
      build\x64-Debug (default)\main.obj : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const precice::logging::BackendConfiguration::default_filter" (?default_filter@BackendConfiguration@logging@precice@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
      build\x64-Debug (default)\main.obj : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const precice::logging::BackendConfiguration::default_formatter" (?default_formatter@BackendConfiguration@logging@precice@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)
      build\x64-Debug (default)\ParallelTest.obj : error LNK2001: unresolved external symbol "public: static class std::shared_ptr<class precice::com::Communication> precice::utils::MasterSlave::_communication" (?_communication@MasterSlave@utils@precice@@2V?$shared_ptr@VCommunication@com@precice@@@std@@A)
      build\x64-Debug (default)\RadialBasisFctMappingTest.obj : error LNK2001: unresolved external symbol "public: static class std::shared_ptr<class precice::com::Communication> precice::utils::MasterSlave::_communication" (?_communication@MasterSlave@utils@precice@@2V?$shared_ptr@VCommunication@com@precice@@@std@@A)
      build\x64-Debug (default)\ParallelTests.obj : error LNK2001: unresolved external symbol "public: static class std::shared_ptr<class precice::com::Communication> precice::utils::MasterSlave::_communication" (?_communication@MasterSlave@utils@precice@@2V?$shared_ptr@VCommunication@com@precice@@@std@@A)
      build\x64-Debug (default)\TestContext.obj : error LNK2001: unresolved external symbol "public: static class std::shared_ptr<class precice::com::Communication> precice::utils::MasterSlave::_communication" (?_communication@MasterSlave@utils@precice@@2V?$shared_ptr@VCommunication@com@precice@@@std@@A)
      build\x64-Debug (default)\ExampleTests.obj : error LNK2001: unresolved external symbol "public: static class std::shared_ptr<class precice::com::Communication> precice::utils::MasterSlave::_communication" (?_communication@MasterSlave@utils@precice@@2V?$shared_ptr@VCommunication@com@precice@@@std@@A)
      build\x64-Debug (default)\main.obj : error LNK2001: unresolved external symbol "public: static class std::shared_ptr<class precice::com::Communication> precice::utils::MasterSlave::_communication" (?_communication@MasterSlave@utils@precice@@2V?$shared_ptr@VCommunication@com@precice@@@std@@A)
      build\x64-Debug (default)\ParallelMatrixOperationsTest.obj : error LNK2001: unresolved external symbol "public: static class std::shared_ptr<class precice::com::Communication> precice::utils::MasterSlave::_communication" (?_communication@MasterSlave@utils@precice@@2V?$shared_ptr@VCommunication@com@precice@@@std@@A)
      build\x64-Debug (default)\CommunicateBoundingBoxTest.obj : error LNK2001: unresolved external symbol "public: static class std::shared_ptr<class precice::com::Communication> precice::utils::MasterSlave::_communication" (?_communication@MasterSlave@utils@precice@@2V?$shared_ptr@VCommunication@com@precice@@@std@@A)
      build\x64-Debug (default)\CommunicateMeshTest.obj : error LNK2001: unresolved external symbol "public: static class std::shared_ptr<class precice::com::Communication> precice::utils::MasterSlave::_communication" (?_communication@MasterSlave@utils@precice@@2V?$shared_ptr@VCommunication@com@precice@@@std@@A)
      build\x64-Debug (default)\main.obj : error LNK2001: unresolved external symbol "bool precice::syncMode" (?syncMode@precice@@3_NA)
      build\x64-Debug (default)\RadialBasisFctMappingTest.obj : error LNK2001: unresolved external symbol "bool precice::syncMode" (?syncMode@precice@@3_NA)
      build\x64-Debug (default)\SerialImplicitCouplingSchemeTest.obj : error LNK2001: unresolved external symbol "public: static double const precice::cplscheme::CouplingScheme::UNDEFINED_TIME" (?UNDEFINED_TIME@CouplingScheme@cplscheme@precice@@2NB)
      build\x64-Debug (default)\RTreeTests.obj : error LNK2001: unresolved external symbol "private: static class std::map<int,struct precice::mesh::rtree::MeshIndices,struct std::less<int>,class std::allocator<struct std::pair<int const ,struct precice::mesh::rtree::MeshIndices> > > precice::mesh::rtree::_cached_trees" (?_cached_trees@rtree@mesh@precice@@0V?$map@HUMeshIndices@rtree@mesh@precice@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHUMeshIndices@rtree@mesh@precice@@@std@@@6@@std@@A)
      build\x64-Debug (default)\SerialTests.obj : error LNK2001: unresolved external symbol "public: static class std::vector<struct precice::action::RecorderAction::Record,class std::allocator<struct precice::action::RecorderAction::Record> > precice::action::RecorderAction::records" (?records@RecorderAction@action@precice@@2V?$vector@URecord@RecorderAction@action@precice@@V?$allocator@URecord@RecorderAction@action@precice@@@std@@@std@@A)
      build\x64-Debug (default)\Debug\testprecice.exe : fatal error LNK1120: 9 unresolved externals
      ```

**Comment by fsimonis** [comment]
Just tried to use vcpkg to install the dependencies on Linux with the hope to get it working on Windows in the future.

I used preCICE develop (after 3.1.2) and the following `vcpkg.json` in the project root.

```json
{
  "name": "precice",
  "version-string": "3.1.2",
  "dependencies": [
    "boost-log",
    "boost-program-options",
    "boost-system",
    "boost-thread",
    "boost-test",
    "boost-vmd",
    "boost-preprocessor",
    "boost-container",
    "boost-stacktrace",
    "boost-accumulators",
    "boost-geometry",
    "boost-uuid",
    "eigen3",
    "libxml2",
    "openmpi"
  ]
}
```

I then configured precice with:

```
cmake -DCMAKE_TOOLCHAIN_FILE=/root/vcpkg/scripts/buildsystems/vcpkg.cmake -DPRECICE_FEATURE_PYTHON_ACTIONS=Off -DPRECICE_FEATURE_PETSC_MAPPING=Off  ../precice/
```

This got me to the point where precice and precice-tools compile without python or PETSc.
The test binary fails to compile with
```
/root/precice/src/testing/main.cpp: In function 'int main(int, char**)':
/root/precice/src/testing/main.cpp:123:60: error: '::init_unit_test' has not been declared; did you mean 'init_unit_test_suite'?
  123 |   int       retCode  = boost::unit_test::unit_test_main(&::init_unit_test, argc, argv);
      |                                                            ^~~~~~~~~~~~~~
      |                                                            init_unit_test_suite
```

I cannot explain why this happens. This also happens when using `PRECICE_BUILD_UNITY=OFF`.

Executing `precice-tools` leads to a SEGFAULT in boost.
Solverdummies build, but running them leads to the same SEGFAULT:

```
Program received signal SIGSEGV, Segmentation fault.
0x000073c1294e0946 in boost::intrusive_ptr<boost::log::v2s_mt_posix::attributes::named_scope::impl>::get (this=0x0)
    at /root/precice/vcpkg_installed/x64-linux/include/boost/smart_ptr/intrusive_ptr.hpp:183
183	        return px;
(gdb) bt
#0  0x000073c1294e0946 in boost::intrusive_ptr<boost::log::v2s_mt_posix::attributes::named_scope::impl>::get (this=0x0)
    at /root/precice/vcpkg_installed/x64-linux/include/boost/smart_ptr/intrusive_ptr.hpp:183
#1  0x000073c1294e04a6 in boost::intrusive_ptr<boost::log::v2s_mt_posix::attribute::impl>::intrusive_ptr<boost::log::v2s_mt_posix::attributes::named_scope::impl> (
    this=0x7ffe19ed0b60, rhs=...) at /root/precice/vcpkg_installed/x64-linux/include/boost/smart_ptr/intrusive_ptr.hpp:86
#2  0x000073c1294df474 in boost::log::v2s_mt_posix::attributes::named_scope::named_scope (this=0x7ffe19ed0bc0)
    at /root/vcpkg/buildtrees/boost-log/src/ost-1.85.0-563923ef5e.clean/libs/log/src/named_scope.cpp:277
#3  0x000073c128f6942e in precice::logging::Logger::LoggerImpl::LoggerImpl (this=0x61d78bfbd370, module="math::geometry") at /root/precice/src/logging/Logger.cpp:125
#4  0x000073c128f695d5 in precice::logging::Logger::Logger (this=0x73c129ae5e80 <precice::math::geometry::_log>, module="math::geometry")
    at /root/precice/src/logging/Logger.cpp:129
#5  0x000073c129218e03 in __static_initialization_and_destruction_0 () at /root/precice/src/math/geometry.cpp:14
#6  0x000073c129218e4a in _GLOBAL__sub_I_geometry.cpp(void) () at /root/precice/src/math/geometry.cpp:221
#7  0x000073c129c1571f in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7ffe19ed0d38, env=env@entry=0x7ffe19ed0d48) at ./elf/dl-init.c:74
#8  0x000073c129c15824 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at ./elf/dl-init.c:120
#9  _dl_init (main_map=0x73c129c492e0, argc=1, argv=0x7ffe19ed0d38, env=0x7ffe19ed0d48) at ./elf/dl-init.c:121
#10 0x000073c129c2f5a0 in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#11 0x0000000000000001 in ?? ()
#12 0x00007ffe19ed27fd in ?? ()
#13 0x0000000000000000 in ?? ()
```
