### ISSUE TITLE
Serial integration tests end with segfault (though successful) 

### ISSUE THREAD

**Issue by uekerman** [precice/precice#250]
There is sth wrong with the clean-up of the integration tests. 
When running only the serial integration tests:
```
./tools/compileAndTest.py -t --run_test="PreciceTests/Serial/*"
```
I get a:
```
[1]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
```
but only for two out of the four ranks. 

When running all integration tests, this disappears:
```
./tools/compileAndTest.py -t --run_test="PreciceTests/*/*"
```

**Comment by fsimonis** [comment]
I compiled with `-fsanitize=address` and run `mpirun -np 4 ./testprecice --run_test="PreciceTests/*/*"`.
This is the slightly cleaned-up report:

```
ASAN:SIGSEGV
================================================================
==25170==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7f4f60161774 bp 0x7ffe67baf820 sp 0x7ffe67baf6a0 T0)

ASAN:SIGSEGV
=================================================================
==25169==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7fe3c4afd774 bp 0x7ffd0e0a9f90 sp 0x7ffd0e0a9e10 T0)
    #0 0x7fe3c4afd773 in MPI_Comm_size (/usr/lib/libmpi.so.12+0x57773)
    #0 0x7f4f60161773 in MPI_Comm_size (/usr/lib/libmpi.so.12+0x57773)
    #1 0x7f4f620ad2f2 in precice::utils::EventRegistry::collect()  .../src/utils/EventUtils.cpp:416
    #2 0x7f4f620aa43d in precice::utils::EventRegistry::finalize() .../src/utils/EventUtils.cpp:227
    #1 0x7fe3c6a492f2 in precice::utils::EventRegistry::collect()  .../src/utils/EventUtils.cpp:416
    #2 0x7fe3c6a4643d in precice::utils::EventRegistry::finalize() .../src/utils/EventUtils.cpp:227
    #3 0x8769f6       in main                                      .../src/testing/main.cpp:100
    #4 0x7f4f5cb3982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #5 0x876168       in _start (/tmp/precice/testprecice+0x876168)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 MPI_Comm_size
==25170==ABORTING
    #3 0x8769f6       in main .../src/testing/main.cpp:100
    #4 0x7fe3c14d582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #5 0x876168       in _start (.../testprecice+0x876168)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 MPI_Comm_size
==25169==ABORTING
```

The unknown address `0x000000000010` looks a bit fishy.
